using System;

[assembly: AssemblyTitle("Geta.log4net.Azure")]
[assembly: AssemblyDescription("Log4net azure appender")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Geta")]
[assembly: AssemblyProduct("Geta.log4net.Azure")]
[assembly: AssemblyCopyright("Copyright © 2018 Geta")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: ComVisible(false)]
[assembly: Guid("67E247A8-40A7-4920-BAB4-5609934F6CA4")]
[assembly: AssemblyVersion("2.0.0.0")]
[assembly: AssemblyFileVersion("2.0.0.0")]
[assembly: AssemblyInformationalVersion("2.0.0.0")]